# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1072c04a25c32d137e55f750bc4f7c859513712c299d1298ee65f9fd9c15e63433b7202219204c6a7af7039604a47253249ec04ff2a421fcd484471422f7a4f6

test:
  secret_key_base: efb35d35d8f9e5d13dcfcc7ee2fc877cb15821c67efba77be36ec9d0a8294471660280b2d7eee5d32beab6484e274741bfbe8deee49d93a5bc52c48ee33a08c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
